Add missing translations for Chinese
This will avoid raising Exception "ActionView::Template::Error:
undefined method `pluralize' for 1:Fixnum"
when calling `model_name.human' (used by the gem `kaminari'
in the helper method `page_entries_info'.